# Generated by Django 2.2 on 2021-02-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference', models.CharField(default=' ', max_length=50)),
                ('Budget_Dollar', models.IntegerField(default=' ', max_length=50, null=True)),
                ('Time_Frame_Hour', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
