# Generated by Django 2.2 on 2021-02-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='Budget_Dollar',
            field=models.PositiveIntegerField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='Time_Frame_Hour',
            field=models.PositiveIntegerField(default=' ', max_length=50),
        ),
    ]
