# Generated by Django 2.2 on 2021-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0002_auto_20210226_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='Budget_Dollar',
            field=models.PositiveIntegerField(default=' 5', null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='Time_Frame_Hour',
            field=models.PositiveIntegerField(default=' 5'),
        ),
    ]
