# Generated by Django 2.2 on 2021-03-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selection', '0004_selection_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='author',
        ),
    ]
