# Generated by Django 2.2 on 2021-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recreation_Name', models.CharField(max_length=50)),
                ('Recreation_Type_Indoor', models.CharField(max_length=50)),
                ('Recreation_Type_Outdoor', models.CharField(max_length=50)),
                ('Public', models.CharField(max_length=3)),
                ('Private', models.CharField(max_length=3)),
            ],
        ),
    ]
