# Generated by Django 2.2 on 2021-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='city',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='people',
            name='address',
        ),
        migrations.RemoveField(
            model_name='people',
            name='state',
        ),
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
